# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name (set in params.yaml under hugoblox.branding.name)
title: '铁皮|Actuarial Science & Entrepreneurship '
# Website URL
baseURL: 'https://isalie.github.io/'



############################
## LANGUAGE
############################
languages:
  zh:
    languageName: 中文
    contentDir: content/zh
    menu:
      main:
        - name: 个人简介
          url: '#about'
          weight: 10
        - name: 创业项目
          url: '#projects'
          weight: 20
        - name: 获奖/媒体
          url: '#accomplishments'
          weight: 30
        - name: 精算项目
          url: '#featured'
          weight: 40
        - name: 下载简历
          url: 'uploads/resume-zh.pdf'
          weight: 50
    
  en:
    languageName: English
    contentDir: content/en
    menu:
      main:
        - name: About
          url: '#about'
          weight: 10
        - name: Entrepreneurship
          url: '#projects'
          weight: 20
        - name: Achievements
          url: '#accomplishments'
          weight: 30
        - name: Portfolio
          url: '#featured'
          weight: 40
        - name: Resume
          url: 'uploads/resume-en.pdf'
          weight: 50

defaultContentLanguageInSubdir: true
removePathAccents: true
############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
